INSERT INTO station (name) VALUES ('Aarau');
INSERT INTO station (name) VALUES ('Aathal');
INSERT INTO station (name) VALUES ('Affoltern am Albis');
INSERT INTO station (name) VALUES ('Airolo');
INSERT INTO station (name) VALUES ('Altdorf  (Switzerland)');
INSERT INTO station (name) VALUES ('Altendorf');
INSERT INTO station (name) VALUES ('Ambrì-Piotta');
INSERT INTO station (name) VALUES ('Andelfingen');
INSERT INTO station (name) VALUES ('Arth-Goldau');
INSERT INTO station (name) VALUES ('Au ZH');
INSERT INTO station (name) VALUES ('Bäch');
INSERT INTO station (name) VALUES ('Bad Zurzach');
INSERT INTO station (name) VALUES ('Baden');
INSERT INTO station (name) VALUES ('Balerna');
INSERT INTO station (name) VALUES ('Basel SBB');
INSERT INTO station (name) VALUES ('Basel St. Johann');
INSERT INTO station (name) VALUES ('Bassersdorf');
INSERT INTO station (name) VALUES ('Bauma');
INSERT INTO station (name) VALUES ('Bellinzona');
INSERT INTO station (name) VALUES ('Benken');
-- INSERT INTO station (name) VALUES ('Bern');
INSERT INTO station (name) VALUES ('Biasca');
INSERT INTO station (name) VALUES ('Biberbrugg');
INSERT INTO station (name) VALUES ('Biel/Bienne');
INSERT INTO station (name) VALUES ('Bilten');
INSERT INTO station (name) VALUES ('Birmensdorf');
INSERT INTO station (name) VALUES ('Blumenau');
INSERT INTO station (name) VALUES ('Bodio');
INSERT INTO station (name) VALUES ('Bonstetten-Wettswil');
INSERT INTO station (name) VALUES ('Brig');
INSERT INTO station (name) VALUES ('Brugg');
INSERT INTO station (name) VALUES ('Brunnen');
INSERT INTO station (name) VALUES ('Bubikon');
INSERT INTO station (name) VALUES ('Buchs-Dällikon');
INSERT INTO station (name) VALUES ('Bülach');
INSERT INTO station (name) VALUES ('Cadenazzo');
INSERT INTO station (name) VALUES ('Capolago-Riva San Vitale');
INSERT INTO station (name) VALUES ('Castione-Arbedo');
INSERT INTO station (name) VALUES ('Chiasso');
INSERT INTO station (name) VALUES ('Chur');
INSERT INTO station (name) VALUES ('Dachsen');
INSERT INTO station (name) VALUES ('Delémont');
INSERT INTO station (name) VALUES ('Dielsdorf');
INSERT INTO station (name) VALUES ('Diesbach-Betschwanden');
INSERT INTO station (name) VALUES ('Dietikon');
INSERT INTO station (name) VALUES ('Dietlikon');
INSERT INTO station (name) VALUES ('Dinhard');
INSERT INTO station (name) VALUES ('Dübendorf');
INSERT INTO station (name) VALUES ('Effretikon');
INSERT INTO station (name) VALUES ('Eglisau');
INSERT INTO station (name) VALUES ('Einsiedeln');
INSERT INTO station (name) VALUES ('Elgg');
INSERT INTO station (name) VALUES ('Embrach-Rorbas');
INSERT INTO station (name) VALUES ('Ennenda');
INSERT INTO station (name) VALUES ('Erlenbach ZH');
INSERT INTO station (name) VALUES ('Erstfeld');
INSERT INTO station (name) VALUES ('Etzwilen');
INSERT INTO station (name) VALUES ('Faido');
INSERT INTO station (name) VALUES ('Fehraltorf');
INSERT INTO station (name) VALUES ('Felben-Wellhausen');
INSERT INTO station (name) VALUES ('Feldbach');
INSERT INTO station (name) VALUES ('Fischenthal');
INSERT INTO station (name) VALUES ('Flüelen');
INSERT INTO station (name) VALUES ('Frauenfeld');
INSERT INTO station (name) VALUES ('Freienbach SBB');
INSERT INTO station (name) VALUES ('Freienbach SOB');
INSERT INTO station (name) VALUES ('Fribourg');
INSERT INTO station (name) VALUES ('Geneva Airport');
INSERT INTO station (name) VALUES ('Genève-Cornavin');
INSERT INTO station (name) VALUES ('Gibswil');
INSERT INTO station (name) VALUES ('Giubiasco');
INSERT INTO station (name) VALUES ('Glanzenberg');
INSERT INTO station (name) VALUES ('Glarus');
INSERT INTO station (name) VALUES ('Glattbrugg');
INSERT INTO station (name) VALUES ('Glattfelden');
INSERT INTO station (name) VALUES ('Göschenen');
INSERT INTO station (name) VALUES ('Grüenfeld');
INSERT INTO station (name) VALUES ('Hedingen');
INSERT INTO station (name) VALUES ('Henggart');
INSERT INTO station (name) VALUES ('Herblingen');
INSERT INTO station (name) VALUES ('Herrliberg-Feldmeilen');
INSERT INTO station (name) VALUES ('Hettlingen');
INSERT INTO station (name) VALUES ('Hinwil');
INSERT INTO station (name) VALUES ('Horgen');
INSERT INTO station (name) VALUES ('Horgen Oberdorf');
INSERT INTO station (name) VALUES ('Hüntwangen-Wil');
INSERT INTO station (name) VALUES ('Hurden');
INSERT INTO station (name) VALUES ('Hüttlingen-Mettendorf');
INSERT INTO station (name) VALUES ('Illnau');
INSERT INTO station (name) VALUES ('Interlaken Ost');
INSERT INTO station (name) VALUES ('Interlaken West');
INSERT INTO station (name) VALUES ('Islikon');
INSERT INTO station (name) VALUES ('Jestetten');
INSERT INTO station (name) VALUES ('Jona');
INSERT INTO station (name) VALUES ('Kaiserstuhl AG');
INSERT INTO station (name) VALUES ('Kaltbrunn');
INSERT INTO station (name) VALUES ('Kempraten');
INSERT INTO station (name) VALUES ('Kempten  (Switzerland)');
INSERT INTO station (name) VALUES ('Kemptthal');
INSERT INTO station (name) VALUES ('Kilchberg');
INSERT INTO station (name) VALUES ('Killwangen-Spreitenbach');
INSERT INTO station (name) VALUES ('Kloten');
INSERT INTO station (name) VALUES ('Kloten Balsberg');
INSERT INTO station (name) VALUES ('Knonau');
INSERT INTO station (name) VALUES ('Koblenz  (Switzerland)');
INSERT INTO station (name) VALUES ('Koblenz Dorf');
INSERT INTO station (name) VALUES ('Kollbrunn');
INSERT INTO station (name) VALUES ('Küsnacht Goldbach');
INSERT INTO station (name) VALUES ('Küsnacht ZH');
INSERT INTO station (name) VALUES ('La Chaux-de-Fonds');
INSERT INTO station (name) VALUES ('Lachen');
INSERT INTO station (name) VALUES ('Lamone-Cadempino');
INSERT INTO station (name) VALUES ('Lausanne');
INSERT INTO station (name) VALUES ('Lavorgo');
INSERT INTO station (name) VALUES ('Lenzburg');
INSERT INTO station (name) VALUES ('Othmarsingen');
INSERT INTO station (name) VALUES ('Leuggelbach');
INSERT INTO station (name) VALUES ('Liestal');
INSERT INTO station (name) VALUES ('Linthal');
INSERT INTO station (name) VALUES ('Linthal Braunwaldbahn');
INSERT INTO station (name) VALUES ('Locarno');
INSERT INTO station (name) VALUES ('Lottstetten');
INSERT INTO station (name) VALUES ('Lucerne');
INSERT INTO station (name) VALUES ('Luchsingen-Hätzingen');
INSERT INTO station (name) VALUES ('Lugano');
INSERT INTO station (name) VALUES ('Lugano-Paradiso');
INSERT INTO station (name) VALUES ('Mägenwil');
INSERT INTO station (name) VALUES ('Männedorf');
INSERT INTO station (name) VALUES ('Maroggia-Melano');
INSERT INTO station (name) VALUES ('Märstetten');
INSERT INTO station (name) VALUES ('Marthalen');
INSERT INTO station (name) VALUES ('Meilen');
INSERT INTO station (name) VALUES ('Melide');
INSERT INTO station (name) VALUES ('Mellikon');
INSERT INTO station (name) VALUES ('Mellingen Heitersberg');
INSERT INTO station (name) VALUES ('Mendrisio');
INSERT INTO station (name) VALUES ('Mettmenstetten');
INSERT INTO station (name) VALUES ('Mezzovico');
INSERT INTO station (name) VALUES ('Mitlödi');
INSERT INTO station (name) VALUES ('Montreux');
INSERT INTO station (name) VALUES ('Müllheim-Wigoltingen');
INSERT INTO station (name) VALUES ('Näfels-Mollis');
INSERT INTO station (name) VALUES ('Nänikon-Greifensee');
INSERT INTO station (name) VALUES ('Netstal');
INSERT INTO station (name) VALUES ('Neuchâtel');
INSERT INTO station (name) VALUES ('Neuenhof');
INSERT INTO station (name) VALUES ('Neuhausen');
INSERT INTO station (name) VALUES ('Neuhausen Rheinfall');
INSERT INTO station (name) VALUES ('Nidfurn-Haslen');
INSERT INTO station (name) VALUES ('Nieder- and Oberurnen');
INSERT INTO station (name) VALUES ('Niederglatt');
INSERT INTO station (name) VALUES ('Niederhasli');
INSERT INTO station (name) VALUES ('Niederweningen');
INSERT INTO station (name) VALUES ('Niederweningen Dorf');
INSERT INTO station (name) VALUES ('Oberglatt');
INSERT INTO station (name) VALUES ('Oberrieden');
INSERT INTO station (name) VALUES ('Oberrieden Dorf');
INSERT INTO station (name) VALUES ('Oberwinterthur');
INSERT INTO station (name) VALUES ('Olten');
INSERT INTO station (name) VALUES ('Opfikon');
INSERT INTO station (name) VALUES ('Ossingen');
INSERT INTO station (name) VALUES ('Otelfingen');
INSERT INTO station (name) VALUES ('Otelfingen Golfpark');
INSERT INTO station (name) VALUES ('Palézieux');
INSERT INTO station (name) VALUES ('Palézieux-Village');
INSERT INTO station (name) VALUES ('Pfäffikon SZ');
INSERT INTO station (name) VALUES ('Pfäffikon ZH');
INSERT INTO station (name) VALUES ('Pfungen-Neftenbach');
INSERT INTO station (name) VALUES ('Rafz');
INSERT INTO station (name) VALUES ('Rämismühle-Zell');
INSERT INTO station (name) VALUES ('Rapperswil');
INSERT INTO station (name) VALUES ('Räterschen');
INSERT INTO station (name) VALUES ('Regensdorf-Watt');
INSERT INTO station (name) VALUES ('Reichenburg');
INSERT INTO station (name) VALUES ('Rekingen AG');
INSERT INTO station (name) VALUES ('Reutlingen');
INSERT INTO station (name) VALUES ('Rheineck');
INSERT INTO station (name) VALUES ('Richterswil');
INSERT INTO station (name) VALUES ('Rickenbach-Attikon');
INSERT INTO station (name) VALUES ('Riedmatt');
INSERT INTO station (name) VALUES ('Rietheim');
INSERT INTO station (name) VALUES ('Rikon');
INSERT INTO station (name) VALUES ('Rivera-Bironico');
INSERT INTO station (name) VALUES ('Romanshorn');
INSERT INTO station (name) VALUES ('Rümikon AG');
INSERT INTO station (name) VALUES ('Rümlang');
INSERT INTO station (name) VALUES ('Rüschlikon');
INSERT INTO station (name) VALUES ('Rüti GL');
INSERT INTO station (name) VALUES ('Rüti ZH');
INSERT INTO station (name) VALUES ('Saland');
INSERT INTO station (name) VALUES ('Samstagern');
INSERT INTO station (name) VALUES ('Schaffhausen');
INSERT INTO station (name) VALUES ('Schänis');
INSERT INTO station (name) VALUES ('Schindellegi-Feusisberg');
INSERT INTO station (name) VALUES ('Schlieren');
INSERT INTO station (name) VALUES ('Schloss Laufen am Rheinfall');
INSERT INTO station (name) VALUES ('Schmerikon');
INSERT INTO station (name) VALUES ('Schöfflisdorf-Oberweningen');
INSERT INTO station (name) VALUES ('Schottikon');
INSERT INTO station (name) VALUES ('Schübelbach-Buttikon');
INSERT INTO station (name) VALUES ('Schwanden');
INSERT INTO station (name) VALUES ('Schwerzenbach');
INSERT INTO station (name) VALUES ('Schwyz');
INSERT INTO station (name) VALUES ('Sennhof-Kyburg');
INSERT INTO station (name) VALUES ('Seuzach');
INSERT INTO station (name) VALUES ('Siebnen-Wangen');
INSERT INTO station (name) VALUES ('Sihlbrugg');
INSERT INTO station (name) VALUES ('Sisikon');
INSERT INTO station (name) VALUES ('Solothurn');
INSERT INTO station (name) VALUES ('St. Gallen');
INSERT INTO station (name) VALUES ('Stäfa');
INSERT INTO station (name) VALUES ('Stammheim');
INSERT INTO station (name) VALUES ('Steg');
INSERT INTO station (name) VALUES ('Stein am Rhein');
INSERT INTO station (name) VALUES ('Baar');
INSERT INTO station (name) VALUES ('Steinhausen');
INSERT INTO station (name) VALUES ('Tann-Dürnten');
INSERT INTO station (name) VALUES ('Taverne-Torricella');
INSERT INTO station (name) VALUES ('Thalheim-Altikon');
INSERT INTO station (name) VALUES ('Thalwil');
INSERT INTO station (name) VALUES ('Thayngen');
INSERT INTO station (name) VALUES ('Turbenthal');
INSERT INTO station (name) VALUES ('Turgi');
INSERT INTO station (name) VALUES ('Uerikon');
INSERT INTO station (name) VALUES ('Uetikon');
INSERT INTO station (name) VALUES ('Urdorf');
INSERT INTO station (name) VALUES ('Urdorf Weihermatt');
INSERT INTO station (name) VALUES ('Uster');
INSERT INTO station (name) VALUES ('Uznach');
INSERT INTO station (name) VALUES ('Vallorbe');
INSERT INTO station (name) VALUES ('Vevey');
INSERT INTO station (name) VALUES ('Visp');
INSERT INTO station (name) VALUES ('Wädenswil');
INSERT INTO station (name) VALUES ('Wald');
INSERT INTO station (name) VALUES ('Wallisellen');
INSERT INTO station (name) VALUES ('Weinfelden');
INSERT INTO station (name) VALUES ('Wettingen');
INSERT INTO station (name) VALUES ('Wetzikon');
INSERT INTO station (name) VALUES ('Wiesendangen');
INSERT INTO station (name) VALUES ('Wila');
INSERT INTO station (name) VALUES ('Wilen');
INSERT INTO station (name) VALUES ('Winkel am Zürichsee');
INSERT INTO station (name) VALUES ('Winterthur Grüze');
-- INSERT INTO station (name) VALUES ('Winterthur');
INSERT INTO station (name) VALUES ('Winterthur Seen');
INSERT INTO station (name) VALUES ('Winterthur Töss');
INSERT INTO station (name) VALUES ('Winterthur Wallrüti');
INSERT INTO station (name) VALUES ('Winterthur Wülflingen');
INSERT INTO station (name) VALUES ('Wohlen');
INSERT INTO station (name) VALUES ('Wollerau');
INSERT INTO station (name) VALUES ('Würenlos');
INSERT INTO station (name) VALUES ('Ziegelbrücke');
INSERT INTO station (name) VALUES ('Zollikon');
INSERT INTO station (name) VALUES ('Zug');
INSERT INTO station (name) VALUES ('Zürich Airport');
INSERT INTO station (name) VALUES ('Zürich Altstetten');
INSERT INTO station (name) VALUES ('Zürich Enge');
INSERT INTO station (name) VALUES ('Zürich Hardbrücke');
-- INSERT INTO station (name) VALUES ('Zürich Hauptbahnhof');
INSERT INTO station (name) VALUES ('Zürich Oerlikon');
INSERT INTO station (name) VALUES ('Zürich Stadelhofen');
INSERT INTO station (name) VALUES ('Zürich Tiefenbrunnen');
INSERT INTO station (name) VALUES ('Zürich Wiedikon');
INSERT INTO station (name) VALUES ('Zürich Wipkingen');
INSERT INTO station (name) VALUES ('Zürich Wollishofen');
INSERT INTO station (name) VALUES ('Zweidlen');
